//docker run                        \
// --name elasticsearch_container  \
//  -p 9200:9200                    \
//  -p 9300:9300                    \
//  -e "discovery.type=single-node" \
//  docker.elastic.co/elasticsearch/elasticsearch:6.3.2

//docker run \
//  --name kibana \
//  -p 5601:5601 \
//  --link elasticsearch_container:elasticsearch_alias \
//  -e "ELASTICSEARCH_URL=http://elasticsearch_alias:9200" \
//  docker.elastic.co/kibana/kibana:6.3.2
@url = http://127.0.0.1:9200


### Post vehicle
PUT {{url}}/business/building/110
Content-Type: application/json

{
  "address": "57 New Dover Ln",
  "floors": 10,
  "officies": 21,
  "loc": {
      "lat": 40.707519,
      "lon": -74.008560
  }
}

### Get
GET {{url}}/business

### Post vehicle
PUT {{url}}/business/building/217
Content-Type: application/json

{
  "address": "11 Pen Ave",
  "floors": 5,
  "officies": 7,
  "price": 450000,
  "loc": {
      "lat": 40.693519,
      "lon": -73.988560
  }
}

###PUT employee
PUT {{url}}/employees/_doc/331
Content-Type: application/json 

{
    "name": "Steve Honor",
    "title": "Attorney",
    "salary_usd": 140000.00,
    "hiredate": "Oct 10, 2010"
}

###PUT employee
PUT {{url}}/contracts/_doc/9987
Content-Type: application/json 

{
    "name": "property renovation",
    "date_signed": "July 26, 2010",
    "employees_involved": [331, 330, 398]
}

### Get
GET {{url}}/business/_search
Content-Type: application/json 

{
    "query": {
        "term": {
            "address": "pen"
        }
    }
}

### Get
GET {{url}}/business/_search
Content-Type: application/json 

{
    "query": {
        "match_all": {}
    }
}

###curl
curl -XGET "{{url}}/business/_search" -H 'Content-Type: application/json' -d'
{
    "query": {
        "match_all": {}
    }
}'