version: "3"

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks: 
      - logging-network
    ports:
      - 9200:9200

  

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    depends_on:
      - elasticsearch
    ports: 
      - 5601:5601
    networks: 
      - logging-network

  
networks: 
  logging-network:
    driver: bridge