//docker run                        \
// --name elasticsearch_container  \
//  -p 9200:9200                    \
//  -p 9300:9300                    \
//  -e "discovery.type=single-node" \
//  docker.elastic.co/elasticsearch/elasticsearch:6.3.2

//docker run \
//  --name kibana \
//  -p 5601:5601 \
//  --link elasticsearch_container:elasticsearch_alias \
//  -e "ELASTICSEARCH_URL=http://elasticsearch_alias:9200" \
//  docker.elastic.co/kibana/kibana:6.3.2
@url = http://127.0.0.1:9200


### Post vehicle
PUT {{url}}/vehicles/car/123
Content-Type: application/json

{
  "make": "Honda",
  "Color": "Black",
  "HP": 250,
  "milage": 24000,
  "price": 19300.97
}